apiVersion: v1
kind: ConfigMap
metadata:
  name: crypto-monitor-config
  namespace: app
data:
  SPRING_PROFILES_ACTIVE: "k8s"
  TZ: "Asia/Taipei"
  DB_HOST: "crypto-monitor-postgres"
  DB_PORT: "5432"
  DB_NAME: "btctrade"
  DB_USERNAME: "btctrade"
  SERVER_PORT: "8080"
  APP_WEBSOCKET_ALLOWED_ORIGINS: "http://localhost:8080,https://crypto-monitor.kubeinpocket.com"
